# Generated by Django 5.0.6 on 2024-05-28 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number_of_games', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='games_names',
            field=models.CharField(default='prout', max_length=100),
        ),
        migrations.AddField(
            model_name='tournament',
            name='player_names',
            field=models.CharField(default='gpt', max_length=100),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.tournament')),
            ],
        ),
    ]
