# Generated by Django 5.0.6 on 2024-05-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_game_tournament_games_names_tournament_player_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tournament',
        ),
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ManyToManyField(to='tournament.tournament'),
        ),
    ]
